### PR TITLE
Add parameter that makes it possible to attach openapi.yaml files

### PR DESCRIPTION
**Pull request by maddingo**
This PR also improves the java doc comments (They are displayed on `mvn springdoc-openapi:help -Ddetail=true`)

### CODE REVIEW

**Comment by maddingo** [comment]
This PR fixes #23

**Comment by vb-chris** [comment]
Although this PR was merged into master, [version 1.3 from Maven Central](https://repo1.maven.org/maven2/org/springdoc/springdoc-openapi-maven-plugin/1.3/) does not contain the introduced configuration parameter `outputFileType`. How is that possible?

**Comment by bnasslahsen** [comment]
The objectif of the PR, is to make it possible to attach `openapi.yaml` files as well.
This is being resolved without any additional parameter. https://github.com/springdoc/springdoc-openapi-maven-plugin/commit/c0a46512adfa641d303ca4f20623e83d17cf988e

**Comment by vb-chris** [comment]
OK, I see, but the file extension and classifier of the attached artifact seem to be `json` even if the format is YAML.

**Comment by bnasslahsen** [comment]
see the thread here: https://github.com/springdoc/springdoc-openapi-maven-plugin/issues/23

**Pull request merged**
