### PR TITLE
fixed output file encoding (utf-8)

### PR DESCRIPTION
**Pull request by alex-kabin**

### CODE REVIEW

**Comment by LEZIER-S2** [comment]
Hello 

@alex-kabin @ltomes @bnasslahsen do you know when this PR will be merged ?

Best regard

**Comment by LEZIER-S2** [comment]
Hello 

@alex-kabin @ltomes @bnasslahsen do you know when this PR will be merged ?

Best regard

**Comment by alex-kabin** [comment]
@LEZIER-S2 dont know really( You can just clone my fork and build yourself. Also you can use plugin from local maven repository just now

**Comment by LEZIER-S2** [comment]
Thanks @alex-kabin, until the correction is merged I will use this palliative.

**Comment by bnasslahsen** [comment]
Hi @LEZIER-S2, 

 The merege and the release will be done today.

**Comment by bnasslahsen** [comment]
The v0.3 of the plugin is now published to maven central.

**Pull request merged**
